import React, { useState } from 'react';
import {
  Database,
  Network,
} from 'lucide-react';

const CANONICAL_TAXONOMY = [
  { tag: 'OBSERVED', color: 'bg-emerald-50 text-emerald-700 border-emerald-200', desc: 'Direct empirical measurements from Earth Observation or physical in-situ sensors (e.g. Sentinel-1 GRD, CWC gauge records).' },
  { tag: 'REPORTED', color: 'bg-blue-50 text-blue-700 border-blue-200', desc: 'Authoritative administrative or institutional records (e.g. CWC Tehri Dam height = 260.5 m, THDC storage capacity).' },
  { tag: 'ASSUMED', color: 'bg-amber-50 text-amber-700 border-amber-200', desc: 'Numerical or engineering parameter estimates adopted where site-specific data are absent (e.g. uniform Manning n = 0.06).' },
  { tag: 'MODELLED', color: 'bg-indigo-50 text-indigo-700 border-indigo-200', desc: 'Computed outputs generated by physics-based numerical solvers (e.g. DualSPHysics Lagrangian particles, LISFLOOD-FP water depths).' },
  { tag: 'DERIVED', color: 'bg-purple-50 text-purple-700 border-purple-200', desc: 'Secondary products computed from primary model rasters (e.g. vector inundation contours, spatial intersection buffers).' },
  { tag: 'PRECOMPUTED MODEL RESULT', color: 'bg-cyan-50 text-cyan-700 border-cyan-200', desc: 'Verified benchmark simulation packages persisted in storage to provide instant, reproducible reference comparisons.' },
  { tag: 'CONTEXT DATA', color: 'bg-slate-100 text-slate-700 border-slate-200', desc: 'External spatial base layers used for environmental context (e.g. OpenStreetMap road lines, settlement points).' },
];

const DATASETS = [
  {
    id: 'copernicus_dem',
    source: 'Copernicus GLO-30 DEM',
    provider: 'European Space Agency (ESA)',
    purpose: 'Hydraulic Domain & Terrain Definition',
    taxonomy: 'OBSERVED',
    resolution: '30 m posting',
    processing: 'Hydrologic conditioning, canyon valley enforcement, and ASCII raster generation for LISFLOOD-FP 8.1.',
  },
  {
    id: 'sentinel1',
    source: 'Sentinel-1 C-SAR (GRD)',
    provider: 'Copernicus / Google Earth Engine',
    purpose: 'Bitemporal Surface-Water Change Detection',
    taxonomy: 'OBSERVED',
    resolution: '10 m / 30 m analysis',
    processing: 'IW mode, VV polarization, relative orbit matching, speckle filtering, and local Otsu discriminant thresholding.',
  },
  {
    id: 'osm_roads',
    source: 'OpenStreetMap Road Network',
    provider: 'OSM Contributors / Geofabrik',
    purpose: 'Critical Infrastructure & Evacuation Routing',
    taxonomy: 'CONTEXT DATA',
    resolution: 'Vector LineString',
    processing: 'Road network topology extraction, planarization for Dijkstra shortest-path evaluation, and wetted buffer clipping.',
  },
  {
    id: 'cwc_dam_meta',
    source: 'Tehri Dam Structural Register',
    provider: 'Central Water Commission (CWC) / THDC',
    purpose: 'Breach Source Boundary Constraints',
    taxonomy: 'REPORTED',
    resolution: 'Embankment Specifications',
    processing: 'Crest elevation (839.5 m MSL), hydraulic head (260.5 m), and gross storage capacity (3.54 BCM) utilized for Froehlich breach scaling.',
  },
  {
    id: 'manning_friction',
    source: 'Uniform Channel Friction Roughness',
    provider: 'Engineering Assumption',
    purpose: 'Bed Resistance Formulation',
    taxonomy: 'ASSUMED',
    resolution: 'Manning n = 0.06',
    processing: 'Uniform roughness coefficient adopted for steep boulder-bed Himalayan mountain gorge reach.',
  },
];

const PIPELINE_CHAIN = [
  { step: '1. Hydrology Context', out: 'Event Rainfall-Runoff', tag: 'CONCEPTUAL MODEL' },
  { step: '2. Theoretical Breach', out: 'Froehlich Geometry', tag: 'ASSUMED' },
  { step: '3. Near-Field SPH', out: 'DualSPHysics Transect', tag: 'MODELLED' },
  { step: '4. Boundary Coupling', out: '300k m³/s Hydrograph', tag: 'DERIVED' },
  { step: '5. Far-Field 2D', out: 'LISFLOOD-FP Depth Rasters', tag: 'MODELLED' },
  { step: '6. Spatial Exposure', out: 'OSM Asset Intersections', tag: 'DERIVED' },
  { step: '7. Tactical HADR', out: 'Hazard-Aware Routing', tag: 'DERIVED' },
];

export default function DataProvenance() {
  const [selectedDataset, setSelectedDataset] = useState(DATASETS[0]);

  return (
    <div className="h-full flex flex-col bg-slate-50 text-slate-800 overflow-y-auto">
      {/* Top Banner */}
      <div className="bg-white border-b border-slate-200 px-6 py-4 flex items-center justify-between shrink-0 shadow-2xs">
        <div>
          <h1 className="text-xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <Database className="w-5 h-5 text-blue-600" />
            Data Catalog &amp; Scientific Provenance
          </h1>
          <p className="text-xs text-slate-500">
            Explicit tracking of observational sources, reported geometry, mathematical models, and operational assumptions.
          </p>
        </div>
      </div>

      <div className="p-6 max-w-6xl mx-auto w-full space-y-6 flex-1">
        {/* Taxonomy Definitions Grid */}
        <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs space-y-3">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-500">
            Standardized Scientific Provenance Taxonomy
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {CANONICAL_TAXONOMY.map((item) => (
              <div key={item.tag} className="border border-slate-200 rounded-lg p-3 bg-slate-50/50 space-y-1">
                <span className={`inline-block px-2 py-0.5 rounded text-[10px] font-bold border ${item.color}`}>
                  {item.tag}
                </span>
                <p className="text-[11px] text-slate-600 leading-snug">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Pipeline Lineage Chain */}
        <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs space-y-3">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-500 flex items-center gap-2">
            <Network className="w-4 h-4 text-purple-600" />
            Physics Pipeline Data Lineage
          </h2>
          <div className="flex items-center gap-2 overflow-x-auto pb-2">
            {PIPELINE_CHAIN.map((stage, idx) => (
              <React.Fragment key={stage.step}>
                <div className="flex-none bg-slate-50 border border-slate-200 rounded-lg p-3 text-center min-w-[130px]">
                  <span className="text-[10px] font-bold text-slate-400 uppercase block mb-0.5">
                    {stage.step}
                  </span>
                  <span className="text-xs font-bold text-slate-800 block">{stage.out}</span>
                  <span className="inline-block mt-1 px-1.5 py-0.5 rounded text-[9px] font-mono font-semibold bg-white border border-slate-200 text-slate-600">
                    {stage.tag}
                  </span>
                </div>
                {idx < PIPELINE_CHAIN.length - 1 && (
                  <span className="text-slate-300 font-bold">&rarr;</span>
                )}
              </React.Fragment>
            ))}
          </div>
        </div>

        {/* Canonical Datasets Table + Inspector */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
          <div className="lg:col-span-2 bg-white border border-slate-200 rounded-xl p-5 shadow-xs space-y-3">
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-500">
              Registered Spatial &amp; Geophysical Datasets
            </h2>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead className="bg-slate-50 border-b border-slate-200 text-slate-600 font-semibold font-mono text-[11px]">
                  <tr>
                    <th className="p-2.5">Dataset Name</th>
                    <th className="p-2.5">Provider</th>
                    <th className="p-2.5">Provenance Tag</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 text-[11px]">
                  {DATASETS.map((d) => (
                    <tr
                      key={d.id}
                      onClick={() => setSelectedDataset(d)}
                      className={`cursor-pointer transition ${
                        selectedDataset?.id === d.id ? 'bg-blue-50/60 font-semibold' : 'hover:bg-slate-50'
                      }`}
                    >
                      <td className="p-2.5 text-slate-900">{d.source}</td>
                      <td className="p-2.5 text-slate-600">{d.provider}</td>
                      <td className="p-2.5">
                        <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-slate-100 text-slate-700">
                          {d.taxonomy}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Dataset Detail Card */}
          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs flex flex-col justify-between space-y-3 text-xs">
            {selectedDataset ? (
              <div className="space-y-3">
                <div className="border-b border-slate-100 pb-2">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                    Dataset Inspection
                  </span>
                  <h3 className="font-bold text-slate-900 text-sm mt-0.5">{selectedDataset.source}</h3>
                </div>

                <div className="space-y-2 text-[11px]">
                  <div>
                    <span className="text-slate-400 block text-[10px] uppercase font-bold">Provider</span>
                    <span className="text-slate-800 font-medium">{selectedDataset.provider}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block text-[10px] uppercase font-bold">Purpose</span>
                    <span className="text-slate-800 font-medium">{selectedDataset.purpose}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block text-[10px] uppercase font-bold">Resolution</span>
                    <span className="font-mono text-slate-700">{selectedDataset.resolution}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block text-[10px] uppercase font-bold">Processing Description</span>
                    <p className="text-slate-600 leading-relaxed mt-0.5">{selectedDataset.processing}</p>
                  </div>
                </div>
              </div>
            ) : (
              <div className="text-slate-400 text-center py-8">Select a dataset to inspect details.</div>
            )}

            <div className="p-2.5 rounded bg-blue-50 border border-blue-100 text-[10px] text-blue-800">
              <strong>Usage Policy:</strong> Strictly bounded to emergency planning research. Physical validation not available.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
